let song_list = {
  "01": {
    title: "Kids In Love ",
    artist: "Kygo",
    genre: "Dance",
    duration: "4:22",
    track: "Kids In Love (feat. Night Game)",
  },
  "02": {
    title: "Sunrise ",
    artist: "Kygo",
    genre: "Dance",
    duration: "3:34",
    track: "Sunrise (feat. Jason Walker)",
  },
  "03": {
    title: "This Town ",
    artist: "Kygo",
    genre: "Dance",
    duration: "3:22",
    track: "This Town (feat. Sasha Sloan)",
  },
  "04": {
    title: "Stay ",
    artist: "Kygo",
    genre: "Dance",
    duration: "3:59",
    track: "Stay",
  },
  "05": {
    title: "Never Let You Go ",
    artist: "Kygo",
    genre: "Dance",
    duration: "3:53",
    track: "Never Let You Go (feat. John Newman)",
  },
  "06": {
    title: "Firestone",
    artist: "Kygo",
    genre: "Dance",
    duration: "4:33",
    track: "Firestone",
  },
  "07": {
    title: "Stranger Things",
    artist: "Kygo",
    genre: "Dance",
    duration: "3:41",
    track: "Stranger Things (feat. OneRepublic)",
  },
  "08": {
    title: "Oasis",
    artist: "Kygo",
    genre: "Dance",
    duration: "3:57",
    track: "Oasis",
  },
  "09": {
    title: "Fragile",
    artist: "Kygo",
    genre: "Dance",
    duration: "3:51",
    track: "Fragile",
  },
  10: {
    title: "It Aint Me ",
    artist: "Kygo",
    genre: "Dance",
    duration: "3:40",
    track: "It Aint Me (feat. Selena Gomez)",
  },
};
